### ISSUE TITLE
Indicador de carga en pantalla de login es horrible

### ISSUE THREAD

**Issue by ThomasMiz** [ThomasMiz/GYM-AndroidApp#22]
pq usa la pantalla entera? Mientras está cargando deshabilitar los campos, poner el circular loader adentro del botón de login y sacarle el texto, sino queda horrible

**Comment by ichayer** [comment]
Trank, ahora lo corrijo, necesitaba algo rapido para poder tantear errores y como eso ya estaba implementado lo tome. De hecho fijate que tenemos un problema con el manejo de errores porque la excepcion no maneja el campo details. Directamente te va a mostrar el mensaje default de la excepcion y eso no es claro para entender cual fue el error.

![image](https://user-images.githubusercontent.com/75281625/201747182-34e7ca4b-4d64-483b-8832-bf11b11d646c.png)
